name: Garden CI/CD Pipeline
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
        
      - name: Install Garden CLI
        run: |
          curl -sL https://get.garden.io/install.sh | bash
          export PATH="$HOME/.garden/bin:$PATH"
          echo "$HOME/.garden/bin" >> $GITHUB_PATH
          garden version
          
      - name: Garden Status Check
        run: garden status
        
      - name: Build App with Garden
        run: garden build
        
      - name: Deploy App with Garden
        run: garden deploy
        env:
          # Add your required environment variables here
          GARDEN_AUTH_TOKEN: ${{ secrets.GARDEN_AUTH_TOKEN }}
